### ISSUE TITLE
非master分支该如何构建？

### ISSUE THREAD

**Issue by nobk** [10bits/gedoor-Build#7]
例如从master分支出function1，然后修改了一些代码并提交到分支function1。
应该如何自动构建function1这个分支呢？

**Comment by 10bits** [comment]
```xml
push:
    branches:
      - master
```
master改成你的分支名

**Comment by nobk** [comment]
@10bits  请帮我看下，我编译fn-split-1分支，对自动构建文件 .github/workflows/legado.yml做了如下修改
https://github.com/10bits/gedoor-Build/compare/master...nobk:master
```
on: 
  watch:
    types: [started]
  push:
    branches:
      - fn-split-1
  pull_request:
    branches:
      - fn-split-1
#  schedule:
#    - cron: '0 */6 * * *'
```
我的legado fn-split-1分支的HAED是
980c3e0b0961bb364c49dacf7b35ef57d76e4f6e 从文件名'书名 by 作者.txt'或.epub提取书名、作者 
https://github.com/nobk/legado/commits/fn-split-1

但看日志，并没有成功checkout对应分支的版本，而依然是master分支。
HEAD is now at c13dd1d37 换源添加是否校验作者选项
build_apk  -> clone code
https://github.com/nobk/gedoor-Build/runs/2263487500?check_suite_focus=true


Run source $GITHUB_WORKSPACE/action_clone.sh
Cloning into '/opt/legado'...
Note: switching to '3.21.040323'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at c13dd1d37 换源添加是否校验作者选项

**Comment by nobk** [comment]
自己搞定了，提交PR之前可以在自己的分支下编译一遍然后下载apk测试，省得安装Android Studio
修改一下action_clone.sh文件硬编码指定GIT URL以及分支名称，如果有更优雅的方式请指教。
https://github.com/10bits/gedoor-Build/compare/master...nobk:master

**Comment by 10bits** [comment]
```yml
- uses: actions/checkout@v2
  with:
    ref: 'fn-split-1'
```
https://github.com/actions/checkout
checkout 指定branch
